tasks:
  - name: prereq
    before: |
      source /workspace/aws-networking/bin/installtf
      source ./bin/tfalias
    #  source ./bin/installawscli
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform